name: dotnet package

on: [push]

jobs:
  build_dot_net:
    runs-on: ubuntu-latest

steps:
-name: setup dotnet sdk
- uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '6.0.x'
-name: checkout your source
  uses: actions/checkout@v3
-name: list your repo
  run: ls -LR TestGitHub/bin
-name: build app
  run: dotnet build 
-name: List files after build
  run: ls -LR TestGitHub/bin
